// Generates lib/site/us-map.ts: the US outline, state borders and a set of
// metro positions, already projected (Albers USA, 975 x 610) and rounded.
// The marketing pages draw the talent map from this, so no mapping library
// ships to the browser. Re-run after changing CITIES:  node scripts/gen-us-map.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { feature, mesh } from 'topojson-client';
import { geoAlbersUsa, geoPath } from 'd3-geo';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const us = JSON.parse(readFileSync(join(root, 'node_modules/us-atlas/states-albers-10m.json'), 'utf8'));

const round = d => d.replace(/(\d+\.\d{1})\d+/g, '$1');
const path = geoPath();
const nation = round(path(feature(us, us.objects.nation)));
const borders = round(path(mesh(us, us.objects.states, (a, b) => a !== b)));

// Same projection the albers files were built with.
const projection = geoAlbersUsa().scale(1300).translate([487.5, 305]);
const CITIES = {
  columbus: [-82.9988, 39.9612], cleveland: [-81.6944, 41.4993], cincinnati: [-84.512, 39.1031],
  dublin: [-83.1141, 40.0992], pittsburgh: [-79.9959, 40.4406], philadelphia: [-75.1652, 39.9526],
  harrisburg: [-76.8867, 40.2732], atlanta: [-84.388, 33.749], chicago: [-87.6298, 41.8781],
  newyork: [-74.006, 40.7128], dallas: [-96.797, 32.7767], austin: [-97.7431, 30.2672],
  charlotte: [-80.8431, 35.2271], detroit: [-83.0458, 42.3314], indianapolis: [-86.1581, 39.7684],
  seattle: [-122.3321, 47.6062], sanfrancisco: [-122.4194, 37.7749], boston: [-71.0589, 42.3601],
  washington: [-77.0369, 38.9072], denver: [-104.9903, 39.7392], phoenix: [-112.074, 33.4484],
  tampa: [-82.4572, 27.9506], minneapolis: [-93.265, 44.9778], richmond: [-77.436, 37.5407],
  louisville: [-85.7585, 38.2527], nashville: [-86.7816, 36.1627], raleigh: [-78.6382, 35.7796],
  losangeles: [-118.2437, 34.0522], sandiego: [-117.1611, 32.7157], sacramento: [-121.4944, 38.5816],
  portland: [-122.6765, 45.5231], saltlake: [-111.891, 40.7608], lasvegas: [-115.1398, 36.1699],
  albuquerque: [-106.6504, 35.0844], boise: [-116.2023, 43.615], billings: [-108.5007, 45.7833],
  kansascity: [-94.5786, 39.0997], stlouis: [-90.1994, 38.627], omaha: [-95.9345, 41.2565],
  oklahomacity: [-97.5164, 35.4676], houston: [-95.3698, 29.7604], sanantonio: [-98.4936, 29.4241],
  neworleans: [-90.0715, 29.9511], birmingham: [-86.8025, 33.5186], memphis: [-90.049, 35.1495],
  miami: [-80.1918, 25.7617], orlando: [-81.3792, 28.5383], milwaukee: [-87.9065, 43.0389],
  desmoines: [-93.6091, 41.5868], fargo: [-96.7898, 46.8772], littlerock: [-92.2896, 34.7465],
  hartford: [-72.6851, 41.7658], buffalo: [-78.8784, 42.8864], jackson: [-90.1848, 32.2988],
  anchorage: [-149.9003, 61.2181], honolulu: [-157.8583, 21.3069], cheyenne: [-104.8202, 41.14],
  siouxfalls: [-96.7311, 43.5446], portlandme: [-70.2553, 43.6591], charleston: [-81.6326, 38.3498],
};
const cities = Object.fromEntries(
  Object.entries(CITIES).map(([k, ll]) => {
    const [x, y] = projection(ll);
    return [k, [Math.round(x * 10) / 10, Math.round(y * 10) / 10]];
  }),
);

const out = `// Generated by scripts/gen-us-map.mjs from us-atlas (Albers USA, 975 x 610). Do not edit.
export const US_VIEWBOX = '0 0 975 610';
export const US_NATION = ${JSON.stringify(nation)};
export const US_BORDERS = ${JSON.stringify(borders)};
export const US_CITIES = ${JSON.stringify(cities)} as const;
export type UsCity = keyof typeof US_CITIES;
`;
writeFileSync(join(root, 'lib/site/us-map.ts'), out);
console.log('us-map.ts written', Math.round(out.length / 1024), 'KB');
